backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Landing Page'
        file: 'src/pages/index.md'
        name: 'index'
        fields:
          - { label: Title, name: title, widget: 'string' }
          - { label: Description, name: description, widget: 'string' }
