backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { label: "Title", name: "title", widget: "string" }
